<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class OCookingSettings {
	private $ocooking_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'ocooking_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'ocooking_settings_page_init' ) );
	}

	public function ocooking_settings_add_plugin_page() {
		add_options_page(
			'oCooking Settings', // page_title
			'oCooking Settings', // menu_title
			'manage_options', // capability
			'ocooking-settings', // menu_slug
			array( $this, 'ocooking_settings_create_admin_page' ) // function
		);
	}

	public function ocooking_settings_create_admin_page() {
		$this->ocooking_settings_options = get_option( 'ocooking_settings_option_name' ); ?>

		<div class="wrap">
			<h2>oCooking Settings</h2>
			<p>Paramétrage de notre thème oCooking</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'ocooking_settings_option_group' );
					do_settings_sections( 'ocooking-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function ocooking_settings_page_init() {
		register_setting(
			'ocooking_settings_option_group', // option_group
			'ocooking_settings_option_name', // option_name
			array( $this, 'ocooking_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'ocooking_settings_setting_section', // id
			'Settings', // title
			array( $this, 'ocooking_settings_section_info' ), // callback
			'ocooking-settings-admin' // page
		);

		add_settings_field(
			'facebook_url_0', // id
			'facebook_url', // title
			array( $this, 'facebook_url_0_callback' ), // callback
			'ocooking-settings-admin', // page
			'ocooking_settings_setting_section' // section
		);

		add_settings_field(
			'twitter_url_1', // id
			'twitter_url', // title
			array( $this, 'twitter_url_1_callback' ), // callback
			'ocooking-settings-admin', // page
			'ocooking_settings_setting_section' // section
		);
	}

	public function ocooking_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['facebook_url_0'] ) ) {
			$sanitary_values['facebook_url_0'] = sanitize_text_field( $input['facebook_url_0'] );
		}

		if ( isset( $input['twitter_url_1'] ) ) {
			$sanitary_values['twitter_url_1'] = sanitize_text_field( $input['twitter_url_1'] );
		}

		return $sanitary_values;
	}

	public function ocooking_settings_section_info() {

	}

	public function facebook_url_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="ocooking_settings_option_name[facebook_url_0]" id="facebook_url_0" value="%s">',
			isset( $this->ocooking_settings_options['facebook_url_0'] ) ? esc_attr( $this->ocooking_settings_options['facebook_url_0']) : ''
		);
	}

	public function twitter_url_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="ocooking_settings_option_name[twitter_url_1]" id="twitter_url_1" value="%s">',
			isset( $this->ocooking_settings_options['twitter_url_1'] ) ? esc_attr( $this->ocooking_settings_options['twitter_url_1']) : ''
		);
	}

}
if ( is_admin() )
	$ocooking_settings = new OCookingSettings();

/*
 * Retrieve this value with:
 * $ocooking_settings_options = get_option( 'ocooking_settings_option_name' ); // Array of All Options
 * $facebook_url_0 = $ocooking_settings_options['facebook_url_0']; // facebook_url
 * $twitter_url_1 = $ocooking_settings_options['twitter_url_1']; // twitter_url
 */
